class CreateDShebelievesCup2016Alls < ActiveRecord::Migration[5.0]
  def change
    create_table :d_shebelieves_cup_2016_alls do |t|
      t.string :Player
      t.string :Team
      t.float :MP
      t.float :GS
      t.float :Goals
      t.float :Shots
      t.float :Shots_per_90
      t.float :Shot_Accuracy
      t.float :Shot_GK_Stop
      t.float :Shot_Def_Stop
      t.float :Shot_Miss
      t.float :Shot_Pressd
      t.float :Pct_Shots_Pressd
      t.float :A6_Shots
      t.float :A18_Shots
      t.float :A3L_Shots
      t.float :A3C_Shots
      t.float :A3R_Shots
      t.float :Far_Shots
      t.float :Assists
      t.float :Key_Passes
      t.string :KP_to_Goal
      t.float :Key_Assists
      t.float :Second_Assists
      t.float :Unscored_Key_Passes
      t.float :KP_Goal
      t.float :Assists_per_90
      t.float :Key_Passes_per_90
      t.float :Assists_per_Pass
      t.float :Key_Passes_per_Pass
      t.float :Big_Chances
      t.float :Big_Chances_per_90
      t.float :BC_Scored
      t.float :BC_to_Goal
      t.float :BC_SOG
      t.float :BC_Shot_Miss
      t.float :BC_Dispossess
      t.float :BC_Created
      t.float :BC_Lost
      t.float :Pass_Comp
      t.float :Pass_Att
      t.float :Pass_Comp_Pct
      t.float :opPass_Comp
      t.float :opPass_Att
      t.float :opPass_Comp_Pct
      t.float :opPPass_Comp
      t.float :opPPass_Att
      t.float :opPPass_Comp_Pct
      t.float :Pct_opPass_Pressd
      t.float :rFreq_Pass_Fwd
      t.float :rFreq_Pass_Side
      t.float :rFreq_Pass_Back
      t.float :fwPass_Comp
      t.float :fwPass_Att
      t.float :fwPass_Comp_Pct
      t.float :sPass_Comp
      t.float :sPass_Att
      t.float :sPass_Comp_Pct
      t.float :bPass_Comp
      t.float :bPass_Att
      t.float :bPass_Comp_Pct
      t.float :rFreq_opPass_Fwd
      t.float :rFreq_opPass_Side
      t.float :rFreq_opPass_Back
      t.float :fwopPass_Comp
      t.float :fwopPass_Att
      t.float :fwopPass_Comp_Pct
      t.float :sopPass_Comp
      t.float :sopPass_Att
      t.float :sopPass_Comp_Pct
      t.float :bopPass_Comp
      t.float :bopPass_Att
      t.float :bopPass_Comp_Pct
      t.float :Pct_Pass_Pressd
      t.float :PPass_Comp
      t.float :PPass_Att
      t.float :PPass_Comp_Pct
      t.float :rFreq_PPass_Fwd
      t.float :rFreq_PPass_Side
      t.float :rFreq_PPass_Back
      t.float :fwPPass_Comp
      t.float :fwPPass_Att
      t.float :fwPPass_Comp_Pct
      t.float :sPPass_Comp
      t.float :sPPass_Att
      t.float :sPPass_Comp_Pct
      t.float :bPPass_Comp
      t.float :bPPass_Att
      t.float :bPPass_Comp_Pct
      t.float :Cross_Comp
      t.float :Cross_Att
      t.float :Cross_Att_per_90
      t.float :Cross_Att_per_Pass
      t.float :Cross_Att_per_opPass
      t.float :Cross_Comp_Pct
      t.float :Corner_Crosses
      t.float :Deep_Crosses
      t.float :Launch_Comp
      t.float :Launch_Att
      t.float :Launch_Att_per_90
      t.float :Launch_Att_per_Pass
      t.float :Launch_Att_per_opPass
      t.float :Launch_Comp_Pct
      t.float :Through_Comp
      t.float :Through_Att
      t.float :Through_Att_per_90
      t.float :Through_Att_per_Pass
      t.float :Through_Att_per_opPass
      t.float :Through_Comp_Pct
      t.float :Throw_In_Comp
      t.float :Throw_In_Att
      t.float :Throw_In_Att_per_90
      t.float :Throw_In_Att_per_Pass
      t.float :Throw_In_Comp_Pct
      t.float :Corner_Kicks_Completed
      t.string :CK_Effectiveness
      t.float :Corner_Kicks_Taken
      t.float :CK_Assist
      t.float :CK_Key_Pass
      t.float :FK_Pass_Comp
      t.string :FK_Pass_Comp_Pct
      t.float :FK_Pass_Att
      t.float :FK_Assist
      t.float :FK_Key_Pass
      t.float :FK_Shot
      t.float :FK_Scored
      t.float :Free_Kicks_Taken
      t.float :TO_Won
      t.float :TO_Win_Pct
      t.float :Take_Ons
      t.float :TO_Lost
      t.float :Dispossessed
      t.float :Lost_Touches
      t.float :AD_Won
      t.float :AD_Win_Pct
      t.float :Aerial_Duels
      t.float :AD_Lost
      t.float :Tackles
      t.float :Dispossesses
      t.float :Dribbled
      t.float :Press_Opp
      t.float :Challenge_Opp
      t.float :Recoveries
      t.float :Def_Recoveries
      t.float :Poss_Recoveries
      t.float :Interceptions
      t.float :Blocks
      t.float :Clearances
      t.float :Balls_Shields
      t.float :Saves
      t.float :Goals_Allowed
      t.float :SOG_Faced
      t.string :GperSOG
      t.float :BC_SOG_Faced
      t.float :BC_Saves
      t.float :BC_Goals_Allowed
      t.string :GperBCSOG
      t.float :High_Balls
      t.float :HB_Won
      t.float :HB_Lost
      t.float :HB_Caught
      t.float :HB_Punched
      t.float :HB_Parried
      t.float :HB_Collected
      t.float :HB_Fouls_Won
      t.float :Crosses
      t.float :Crosses_Won
      t.float :Crosses_Lost
      t.float :Corner_Kicks
      t.float :CKs_Won
      t.float :CKs_Lost
      t.float :Free_Kicks
      t.float :FKs_Won
      t.float :FKs_Lost
      t.float :Smothers_Won
      t.float :Smothers_Lost
      t.float :All_Pass_Comp
      t.string :Distribution_Success
      t.float :All_Pass_Att
      t.float :Throw_Comp
      t.string :Throw_Comp_Pct
      t.float :Throw_Att
      t.float :Drop_Kick_Comp
      t.string :Drop_Kick_Comp_Pct
      t.float :Drop_Kick_Att
      t.float :GK_FK_Comp
      t.string :GK_FK_Comp_Pct
      t.float :GK_FK_Att
      t.float :Int_per_90

      t.timestamps
    end
  end
end
